# Ng'anjo OS — systemd-boot entry (Default Kernel)
# Creator: Nehemiah Ng'anjo

title   Ng'anjo OS 1.0 Lite
linux   /arch/boot/x86_64/vmlinuz-linux
initrd  /arch/boot/x86_64/initramfs-linux.img
options archisobasedir=arch archisolabel=NGANJO_OS quiet loglevel=3 systemd.show_status=false udev.log-priority=3 vt.global_cursor_default=0 nowatchdog nmi_watchdog=0 rd.udev.log_priority=3 splash mitigations=off
