# Ng'anjo OS — systemd-boot entry (VM Mode)
# Creator: Nehemiah Ng'anjo

title   Ng'anjo OS 1.0 Lite (VM Mode)
linux   /arch/boot/x86_64/vmlinuz-linux
initrd  /arch/boot/x86_64/initramfs-linux.img
options archisobasedir=arch archisolabel=NGANJO_OS archisodevice=/dev/sr0 nomodeset console=tty0 loglevel=7
