# Ng'anjo OS — systemd-boot entry (Fallback)
# Creator: Nehemiah Ng'anjo

title   Ng'anjo OS 1.0 Lite (Fallback)
linux   /arch/boot/x86_64/vmlinuz-linux
initrd  /arch/boot/x86_64/initramfs-linux-fallback.img
options archisobasedir=arch archisolabel=NGANJO_OS loglevel=5
