# Ng'anjo OS — mkinitcpio configuration for live ISO
MODULES=(sr_mod cdrom isofs loop dm-snapshot)
BINARIES=()
FILES=()
HOOKS=(base udev microcode modconf kms keyboard keymap consolefont plymouth block filesystems archiso)
