---
# Ng'anjo OS — Calamares grubcfg module
efi: true
efiBootloaderId: "nganjo"
installEFI: true
grub:
  id: "nganjo"
  environment: "arch"
distributor: "Ng'anjo OS"
keepDistributor: false
defaultEntry: 0
timeout: 5
