---
# Ng'anjo OS — Calamares unpackfs module

unpack:
  - source: /run/archiso/airootfs
    sourcefs: dir
    destination: ""
    exclude:
      - /etc/sudoers.d/nganjo-live
      - /root/customize_airootfs.sh
      - /root/.automated_script.sh
      - /etc/gdm/custom.conf
