---
modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - initcpiocfg
    - initcpio
    - grubcfg
    - bootloader
    - users
    - networkcfg
    - hwclock
    - services-systemd
    - shellprocess
    - removeuser
    - umount
  - show:
    - finished

branding: nganjo

prompt-install: false
dont-chroot:    false
oem-setup:      false
disable-cancel: false
disable-cancel-during-exec: false

logging: info
